#### Numpy practicals

In [3]:
import numpy as np                                                              # Import NumPy module

'''
Point 1: 
when you import as below

import numpy as np

You access functions inside numpy as np.min(). np is the prefix


Point 2:
You Can also import as below

from numpy import *                         

You access functions inside numpy as min(). Never import libraries this way as it causes confusion
'''

'\nPoint 1: \nwhen you import as below\n\nimport numpy as np\n\nYou access functions inside numpy as np.min(). np is the prefix\n\n\nPoint 2:\nYou Can also import as below\n\nfrom numpy import *                         \n\nYou access functions inside numpy as min(). Never import libraries this way as it causes confusion\n'

#### The Basics

#### ndarray : NumPy is an N-dimensional array
- It describes the collection of items of the same type from zero index. 
- Data-type for each object is dtype.

- Interface is numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
- Parameters are:

        object: Any object exposing the array interface method returns an array or sequence.
        dtype: Data type of array (optional) (Example Below for Complex)
        copy: copy the contents (Optional) (Default is true)
        order: C (row major) or F (column major) or A (any) (default is A)  {Specifies how data is stored in memory. Discussed below}
        subok: By default, returned array forced to be a base class array. If true, sub-classes passed through
        ndmin: Specifies minimum dimensions of resultant array (Example Below for ndmin = 4)

    Row Major Vs Column Major
    ==========================
    Sample 3 x 3 Array
    | 1  2  3 |
    | 4  5  6 |
    | 7  8  9 |
    
    Row Major is stored as below. All Rows together
    |   1   |   2   |   3   |   4   |   5   |   6   |   7   |   8   |   9   |
        
    Column Major is stored as below. All Columns together
    |   1   |   4   |   7   |   2   |   5   |   8   |   3   |   6   |   9   |

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
type(a)                                                                         # ndarray is the object type when ever you create numpy array
                                                                                # It is also referred as NumPy Array or array

numpy.ndarray

In [ ]:
a = np.array([1.1,2.2,3.3], dtype='int32')
print(a)

[1 2 3]


In [ ]:
a = np.array([1.1,2.2,3.3], dtype='float64')
print(a)

[1.1 2.2 3.3]


In [ ]:
b = np.array([[1.1,2.2,3.3],[5.5,6.6,7.7]])
print(b)

[[1.1 2.2 3.3]
 [5.5 6.6 7.7]]


In [ ]:
c = np.array([1, 2, 3])                                                         # Default ndmin is 1 - Single Dimension
print (c)

[1 2 3]


In [ ]:
c = np.array([1, 2, 3], ndmin = 4)                                              # ndmin is 4 - Four Dimension
print (c)

[[[[1 2 3]]]]


In [ ]:
d = np.array([1, 2, 3], dtype = complex) 
print (d)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
student = np.dtype([('name','S20'), ('age', 'int8'), ('marks', 'int32')])       #S - String of 20; int8, int32 - Integer
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print (a)

[(b'abc', 21, 50) (b'xyz', 18, 75)]


In [ ]:
# Get Dimension
a = np.array([1.1,2.2,3.3], dtype='float32')
b = np.array([[1.1,2.2,3.3],[5.5,6.6,7.7]])

print (a.ndim)
print (b.ndim)

1
2


In [ ]:
# Get Shape
print (a.shape)
print (b.shape)

(3,)
(2, 3)


In [ ]:
# Get Type
print (a.dtype)                                                                 # float 32 was specified
print (b.dtype)                                                                 # float64 is default

float32
float64


In [ ]:
# Get Type
print (type(a))                                                                 # float 32 was specified
print (type(b))                                                                 # float64 is default

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Get Size - Length of 1 array element
print (a.itemsize)                                                              # a = np.array([1.1,2.2,3.3], dtype='float32') ==> 32 bit ==> 4 byte
print (b.itemsize)                                                              # float64  ==> 64 bits ==> 8 byte

4
8


In [ ]:
# Get total size - Total Length of all array elements
print (a.nbytes)                                                                # a = np.array([1.1,2.2,3.3], dtype='float32') ==> 32 bit ==> 4 byte. 3 numbers ==> 12 bytes
print (b.nbytes)                                                                # 8 byte. 6 numbers ==> 48 bytes

12
48


In [ ]:
# Get number of elements
print (a.size)                                                                  # a = np.array([1.1,2.2,3.3], dtype='float32') ==> 3 elements present
print (b.size)                                                                  # 6 elements present

3
6


In [ ]:
a = np.array(["1", "2", "3"] , dtype= np.string_)                               # Array from List containing string. Usually you will use Pandas
print (a)
print(a.dtype)                                                                  

a = a.astype('int32')                                                           # type is changed from string to int32
print (a)
print(a.dtype)

[b'1' b'2' b'3']
|S1
[1 2 3]
int32


In [ ]:
# Get Dimension
a = np.array([[1,2,3],[4,5,6]])
b = a

print (a)
print (b)

a[1,1] = 77

print (a)                                                                      
print (b)                                                                       # Note: We only changed in a but b also changed, Never write b = a, as it just assigns a view
                                                                                # use b = a.copy

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 77  6]]
[[ 1  2  3]
 [ 4 77  6]]


In [ ]:
# Get Dimension
a = np.array([[1,2,3],[4,5,6]])
b = a.copy()

print (a)
print (b)

a[1,1] = 77

print (a)                                                                      
print (b)                                                                       # Contents of b is not changed      

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4 77  6]]
[[1 2 3]
 [4 5 6]]


#### numpy.asarray (similar to numpy.array but few parameters)
- Interface is numpy.asarray(a, dtype = None, order = None)
    - a: Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists
    - dtype: data type (default is datatype of a{input data} )
    - order: C (row major) or F (column major) (default is C)


In [ ]:
lista = [1,2,3] 
e = np.asarray(lista) 
print (e)

[1 2 3]


In [ ]:
listtuplea = [(1,2,3),(4,5,6)]                                                    # list of Tuple
e = np.asarray(listtuplea) 
print (e)

[[1 2 3]
 [4 5 6]]


#### numpy.fromiter - Builds an ndarray object from any iterable object
- Interface is numpy.fromiter(iterable, dtype, count = -1)
    - iterable: Iterable object
    - dtype: data type (default is datatype of a{input data} )
    - count: number of items to be read from iterator (efault is -1: read all data)

In [ ]:
list = range(5) 
it = iter(list)  


#for x in it:                                                                   # To see contents of iterator. if you run, value will be lost as iterator wont point to start again
#    print(x)

x = np.fromiter(it, dtype = int,count=-1) 
print (x)

[0 1 2 3 4]


### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,2,3,4,5,6],[7, 8,9,10,11,12]])                                 # Index for Row and Column starts from 0
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
a[1, 5]                                                                         # Get Specific Element - 1st Row/1st index, 5th Column/5th index

12

In [ ]:
a[0, :]                                                                         # Get all Columns - 0th Row, All Columns

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[:, 2]                                                                         # Get all Rows - All Rows, 2nd Column

array([3, 9])

In [ ]:
# Get element between start and end index [startindex:endindex:stepsize]
a[0, 1:-1:1]                                                                    # Row = 0th ; Column = Index 1 untill -1 ; Step = 1.

array([2, 3, 4, 5])

In [ ]:
print ('Before')
print (a)
a[1,5] = 20                                                                     # Change [1,5] from 12 to 20
print ('After')
print(a)



Before
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]
After
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]


In [ ]:
print ('Before')
print (a)
a[:,2] = [1,2]                                                                  # Rows = All, Column = 2. changed form 3,9 to 1,2
print ('After')
print(a)

Before
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 20]]
After
[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11 20]]


In [ ]:
b = np.array([
                [
                    [1,2],
                    [3,4]
                ],
                [
                    [5,6],
                    [7,8]
                ]
            ]) # 3 dimentional array
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[0,0,1]                                                                        # Get a particular element in the array

2

In [ ]:
b[0][0][1]                                                                      # Get a particular element in the array

2

In [ ]:
print ('Before')
print (b)
b[:,:,1] = [[8,8],[9,9]]                                                        # Replace index 1 in the second level with 8,8 and 9,9
print ('After')
print (b)

Before
[[[1 2]
  [8 8]]

 [[5 6]
  [9 9]]]
After
[[[1 8]
  [8 8]]

 [[5 9]
  [9 9]]]


In [ ]:
# Fancy Indexing
# It refers to index defined as list of numbers.

a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]])
print(a[[1,3,2],[0,3,1]])                                                       # Prints (1,0)th element, (3,3)th element and (2,1)th element

a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]])
print(a[[1,3,2]][:, [0,3,1]])                                                   # Prints 1st row, in it 0,3 and 1 column, followed by 3rd row and 2nd row


[ 4 15  9]
[[ 4  7  5]
 [12 15 13]
 [ 8 11  9]]


In [ ]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]])
print(a)
print("====================")

zz1 = a[[1,3,2]]                                                                # Can also be given as zz1 = a[[1,3,2], :]
print(zz1)
print("====================")

zz2 = zz1[:, [0,3,1]]
print(zz2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 4  5  6  7]
 [12 13 14 15]
 [ 8  9 10 11]]
[[ 4  7  5]
 [12 15 13]
 [ 8 11  9]]


In [ ]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15],[16,17,18,19]])
print(a)

print("\nPrint Transpose")                                                      # rows become cl=olumn, column becomes rows 
print(a.T)

print("\nPrint a x a.Transpose")
print(np.dot(a,a.T))


print("\nPrint Transpose using swapaxes - 0,1 and 1,0 will give same result for 2D array. 0,0 and 1,1 will result in no change")
print(a.swapaxes(0,1))                                                          # 0,1 or 1,0 will have same effect as Transpose
print(a.swapaxes(0,0))                                                          # 0,0 or 1,1 will have no effect



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Print Transpose
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]

Print a x a.Transpose
[[  14   38   62   86  110]
 [  38  126  214  302  390]
 [  62  214  366  518  670]
 [  86  302  518  734  950]
 [ 110  390  670  950 1230]]

Print Transpose using swapaxes - 0,1 and 1,0 will give same result for 2D array. 0,0 and 1,1 will result in no change
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
a = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]],[[16,17,18,19],[20,21,22,23]]])
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
print (a.shape)

(3, 2, 4)


#### Initializing Different Types of Arrays
- Interface example is numpy.zeros(shape, dtype = float, order = 'C')
    - Shape - Shape of array 
    - dtype - Desired output data type
    - Order - 'C' for C-style row-major array, 'F' for FORTRAN style column-major array (C is default)
    

In [ ]:
np.zeros((2,3))                                                                 # All 0's Array of 2 x 3, Default type is float 64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.empty((2,3))                                                                 # Most of times it will create 0 but can have some small value as noise, Default type is float 64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,2,2), dtype='int32')                                                 # All 1's Array of 3 x 2 x 2.

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2), 7)                                                               # All 7 Array of 2 x 2

array([[7, 7],
       [7, 7]])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print ('Before')
print (a)
c = np.full_like(a, 4)                                                          # Array with same dimensions as a with value '4'
print ('After')
print (c)

Before
[[1 2 3 4]
 [5 6 7 8]]
After
[[4 4 4 4]
 [4 4 4 4]]


- np.random.rand is for Uniform distribution (in the half-open interval [0.0, 1.0))
- np.random.randn is for Standard Normal (aka. Gaussian) distribution (mean 0 and variance 1)

In [ ]:
np.random.rand(4,2)                                                             # Random number for Array dimension 4 x 2. Default type is float 64

array([[0.19202647, 0.10002682],
       [0.43818814, 0.26913949],
       [0.39544128, 0.07389813],
       [0.33280382, 0.60000353]])

In [ ]:
np.random.randn(4,2)                                                            # Random number for Array dimension 4 x 2. Default type is float 64

array([[-1.86623823, -0.46184308],
       [-0.89790065, -0.4927125 ],
       [ 0.56975296, -0.72644679],
       [-1.08627901,  0.56469905]])

In [ ]:
np.random.randint(-4,8, size=(3,3))                                             # Random integer numbers for Array dimension 3 x 3 between -4 and 8

array([[ 0,  5,  4],
       [-2,  3,  3],
       [-4, -3, -4]])

In [ ]:
np.identity(5)                                                                  # Identity Array dimension 5 x 5. Default type is float 64

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
c = np.array([[1,2,3]])
print ('Before')
print(c)

c = np.repeat(c,3, axis=0)                                                      # Repeat arr (1,2,3) three times on axis 0 - Axis 0 means rows
print ('After')
print(c)

Before
[[1 2 3]]
After
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
c = np.array([[1,2,3]])
print ('Before')
print(c)

c = np.repeat(c,3, axis=1)                                                      # Repeat arr (1,2,3) three times on axis 1 - Axis 1 means column
print ('After')
print(c)

Before
[[1 2 3]]
After
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# Step 1
o = np.ones((5,5))
print ('All 1s Array of 5 x 5')                                                 # All 1 Array of type 5 x 5
print(o)

# Step 2
z = np.zeros((3,3))
print ('\nAll 0s Array of 3 x 3')                                               # All 0 Array of type 0 x 0
print (z)

# Step 3
z[1,1] = 7                                                                      # Change middle element of z Array to 7
print ('\nChanged middle element to 7')
print (z)

# Step 4: Insert Array z (step 2 + 3) into Array o (step 1)
o[1:-1,1:-1] = z
print(o)

All 1s Array of 5 x 5
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

All 0s Array of 3 x 3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Changed middle element to 7
[[0. 0. 0.]
 [0. 7. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematical Operations

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 1                                                                           # Add 1 to all elements in array

# In the above example you added 1 to each element without having to loop. This is also referred as Vectorization in NumPy world

array([2, 3, 4, 5])

In [ ]:
a - 1                                                                           # Subtract 1 from all elements in array

array([0, 1, 2, 3])

In [ ]:
a * 2                                                                           # Multiply 2 to all elements in array

array([2, 4, 6, 8])

In [ ]:
a / 2                                                                           # Divide by 2 to all elements in array

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([7,7,7,0])                                                         # New array 7,7,7,0
a + b                                                                           # Add a=[1 2 3 4] and b=[7,7,7,0]

array([ 8,  9, 10,  4])

In [ ]:
a ** 2                                                                          # Raise to 2 for entire array a=[1 2 3 4]

array([ 1,  4,  9, 16])

In [ ]:
# Feel free to read https://calcworkshop.com/radian-measure/degrees-to-radians/

print(a)
print(np.rad2deg(a))

print (np.sin(a))                                                               # Trignometry functions. Sin for different values

print (np.cos(a))

print (np.tan(a))

[1 2 3 4]
[ 57.29577951 114.59155903 171.88733854 229.18311805]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [ ]:
a_deg = np.array([0,30,45,60,90])                                               # sin values for 0,30,45,60,90 degree
print (np.sin(np.deg2rad(a_deg)))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [ ]:
a = np.ones((2,3))                                                              # All 1s Array of dimension 2 x 3
print(a)

b = np.full((3,2), 2)                                                           # All 2s Array of dimension 3 x 2
print(b)

np.matmul(a,b)                                                                  # Multiply the 2 Array (Note no. of column in 1st Array = 3 and no. of rows in 2nd Array = 3 should be equal)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.array([[1,2], [3,4]])                                                    # New 2x2 Array 
np.linalg.det(c)                                                                # Find Determinant

-2.0000000000000004

In [ ]:
distance = [45,50,35]
speed = [5,10,7]

dist = np.array(distance)
spd = np.array(speed)

print (dist)
print (spd)
print ('---Divide---')
time= dist/spd
print (time)

[45 50 35]
[ 5 10  7]
---Divide---
[9. 5. 5.]


In [ ]:
a = np.array([[6,3,9,1],[6,7,2,9]])
print(a)

b = np.array([[0,5,6,7],[2,9,7,3]])
print(b)

[[6 3 9 1]
 [6 7 2 9]]
[[0 5 6 7]
 [2 9 7 3]]


In [ ]:
a + b

array([[ 6,  8, 15,  8],
       [ 8, 16,  9, 12]])

In [ ]:
a - b

array([[ 6, -2,  3, -6],
       [ 4, -2, -5,  6]])

In [ ]:
a ** b

array([[       1,      243,   531441,        1],
       [      36, 40353607,      128,      729]])

In [ ]:
a > b                                                                           # Element wise compares

array([[ True, False,  True, False],
       [ True, False, False,  True]])

In [ ]:

a = np.random.randint(0, 10, (3, 3))
b = np.count_nonzero(a)                                                            # Count the numbers that are not equal to zero
print(a)                                                                          
print(b)


[[4 0 3]
 [9 3 8]
 [9 9 3]]
8


In [ ]:
a = np.random.randint(0, 10, (3, 3))
b = any(a>5)
print(a)                                                                        # Compare every number in the matrix with greater than 5 or not
print(b)

[[8 3 6]
 [5 2 0]
 [4 0 9]]
True


In [ ]:
np.maximum(a,b)                                                                 # Get maximum element from both the arrays

array([[8, 3, 6],
       [5, 2, 1],
       [4, 1, 9]])

##### Statistics

In [ ]:
a = np.array([[1,2,3],[6,0,4]])
print (a)

[[1 2 3]
 [6 0 4]]


In [ ]:
np.min(a)                                                                       # Minimum in entire Array               

0

In [ ]:
np.max(a)                                                                       # Maximum in entire Array               

6

In [ ]:
np.max(a, axis=0)                                                               # Maximum accross row           

array([6, 2, 4])

In [ ]:
np.max(a, axis=1)                                                               # Maximum across column

array([3, 6])

In [ ]:
np.sum(a, axis=0)                                                               # Sum across row         

array([7, 2, 7])

In [ ]:
a = np.random.randint(5,20, size=9).reshape(3,3) 
m = np.mean(a)                                                                  # Get Mean
s = np.std(a)                                                                   # Get Standard deviation                               
v = np.var(a)                                                                   # Get Variance                                                  
c = np.cov(a)                                                                   # Get Covariance
l= np.log(a)                                                                    # Get Logarithm
cc=np.corrcoef(a)                                                               # Get correlation coefficient                    
print(a)
print('-------------------------')
print("the mean is : ",m)
print('-------------------------')
print("the standard deviation is : ",s)
print('-------------------------')
print("the variance is : \n" , v)
print('-------------------------')
print("the covariance is : \n", c)
print('-------------------------')
print("the logarithm is : \n",l)
print('-------------------------')
print("the correlation coefficient is : \n",cc)

[[11  7  9]
 [11 18 17]
 [12  8 18]]
-------------------------
the mean is :  12.333333333333334
-------------------------
the standard deviation is :  4.055175020198813
-------------------------
the variance is : 
 16.444444444444443
-------------------------
the covariance is : 
 [[ 4.         -7.          4.        ]
 [-7.         14.33333333 -0.33333333]
 [ 4.         -0.33333333 25.33333333]]
-------------------------
the logarithm is : 
 [[2.39789527 1.94591015 2.19722458]
 [2.39789527 2.89037176 2.83321334]
 [2.48490665 2.07944154 2.89037176]]
-------------------------
the correlation coefficient is : 
 [[ 1.         -0.92447345  0.39735971]
 [-0.92447345  1.         -0.01749279]
 [ 0.39735971 -0.01749279  1.        ]]


In [ ]:
np.sum(a, axis=1)                                                               # Sum across row         

array([ 6, 10])

In [ ]:
np.sqrt(a)                                                                      # Square root

array([[1.        , 1.41421356, 1.73205081],
       [2.44948974, 0.        , 2.        ]])

In [ ]:
np.exp(a)                                                                       # Exponent

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003,   1.        , 403.42879349]])

In [ ]:
a > 0

array([[ True,  True,  True],
       [ True, False,  True]])

In [ ]:
(a>0).sum()                                                                     # Count of elements > 0

5

In [ ]:
a = np.array([1,2,3,2,1,3,4,2,1,4,5])
np.unique(a)                                                                    # returns unique elements from array

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1,2,3],[4,0,6]])
print ("Before Sorting")
print (a)

print(a.sort())                                                                 # Sorts in place. Content of array will be changed
print ("\nAfter Sorting contents of a is changed in place")
print(a)

Before Sorting
[[1 2 3]
 [4 0 6]]
None

After Sorting contents of a is changed in place
[[1 2 3]
 [0 4 6]]


In [ ]:
a = np.array([[1,2,3],[4,0,6]])
print ("Before Sorting")
print (a)

print(np.sort(a))                                                               # Sorts in place. Content of array will NOT be changed

print ("\nAfter Sorting contents of a is NOT changed in place")
print(a)

Before Sorting
[[1 2 3]
 [4 0 6]]
[[1 2 3]
 [0 4 6]]

After Sorting contents of a is NOT changed in place
[[1 2 3]
 [4 0 6]]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)

print("\n cumsum axis 0")
print(a.cumsum(axis = 0))                                                       # Cumulative sum across rows
print("\n cumsum axis 1")
print(a.cumsum(axis = 1))                                                       # Cumulative sum across columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 cumsum axis 0
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

 cumsum axis 1
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [ ]:
a = np.array([1.345,2.156,3.333,4.359,6.258])
decNum, wholeNum = np.modf(a)                                                   # Some functions also return multiple array. Returns modulus value
print(decNum, wholeNum)

[0.345 0.156 0.333 0.359 0.258] [1. 2. 3. 4. 6.]


### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])                                        # New 2 x 4 Array
print ('Before')
print(before)
print("shape is " + str(np.shape(before)))

after = before.reshape((4,2))                                                   # Change 2 x 4 Array to 4 x 2 Array
print ('\nAfter')
print(after)
print("shape is " + str(np.shape(after)))

Before
[[1 2 3 4]
 [5 6 7 8]]
shape is (2, 4)

After
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape is (4, 2)


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print ('Before')
print(before)
print("shape is " + str(np.shape(before)))

# Below will give you error
#after = before.reshape((2,3))                                                   # Can Not Change 2 x 4 Array to 2 x 3 Array
#print ('\nAfter')
#print(after)
#print("shape is " + str(np.shape(after)))

Before
[[1 2 3 4]
 [5 6 7 8]]
shape is (2, 4)


In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

np.vstack([a1,a2,a1 + a2])                                                      # Vertical stacking of Arrays

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 6,  8, 10, 12]])

In [ ]:
# Horizontal  stack
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

np.hstack([a1,a2,a1 + a2])                                                      # Horizontal stacking of Arrays

array([ 1,  2,  3,  4,  5,  6,  7,  8,  6,  8, 10, 12])

##### Load Data from File

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a = np.genfromtxt('drive/MyDrive/numpydata.txt', delimiter=',')    # Load Data in numpydata.txt
print (a)
print(a.dtype)                                                                  # For Numpy most cases, data type will be float64

a = a.astype('int32')                                                           # type is changed from default float64 to int32
print (a)
print(a.dtype)

[ 5.  2.  4.  1.  4.  6.  2.  1.  4.  6.  2. 11. 12. 13. 16. 22. 23. 24.
  1.  2. 55.]
float64
[ 5  2  4  1  4  6  2  1  4  6  2 11 12 13 16 22 23 24  1  2 55]
int32


In [ ]:
np.save('savedArrayInDisk', a)                                                  # Saved as Uncompressed Raw Binary File. Check in /content

##### Conitional Statement

In [ ]:
(a > 11)                                                                        # a > 11 

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
       False, False,  True])

In [ ]:
((a > 11) & (a < 22))                                                           # Using and (&)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True, False, False, False,
       False, False, False])

In [ ]:
((a > 11) | (a < 22))                                                           # Using or (|)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
(~((a > 11) | (a < 22)))                                                        # Using not (~)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

##### Boolean Indexing

In [ ]:
names = np.array(["person A", "person B" ,"person C" ,"person D" ,"person E"])
marks = np.random.randint(0,100, size=(5,7))         

print(names)
print(marks)

print('\n person C')
print(names == 'person C')

print('\n person C Marks')
print(marks[names == 'person C'])

print('\n person C Marks in last subject')
print(marks[names == 'person C', -1])

print('\n Other than person C Marks')
cond = names == 'person C'
print(marks[~cond])

print('\n Replaced >35 and <40 Marks with 40')
cond = (marks > 35) &  (marks < 40)
print(cond)
marks[cond] = 40
print(marks)


['person A' 'person B' 'person C' 'person D' 'person E']
[[78 87 94 71 89 57 37]
 [21 24  3 70 76 29 32]
 [33 55 71 57 36 56 35]
 [88 47 25  3 51 14 46]
 [63 22 66  9 60 24 55]]

 person C
[False False  True False False]

 person C Marks
[[33 55 71 57 36 56 35]]

 person C Marks in last subject
[35]

 Other than person C Marks
[[78 87 94 71 89 57 37]
 [21 24  3 70 76 29 32]
 [88 47 25  3 51 14 46]
 [63 22 66  9 60 24 55]]

 Replaced >35 and <40 Marks with 40
[[False False False False False False  True]
 [False False False False False False False]
 [False False False False  True False False]
 [False False False False False False False]
 [False False False False False False False]]
[[78 87 94 71 89 57 40]
 [21 24  3 70 76 29 32]
 [33 55 71 57 40 56 35]
 [88 47 25  3 51 14 46]
 [63 22 66  9 60 24 55]]


##### Conditional Logic

In [ ]:
a = np.array([2,9,6,7,1,5])
b = np.array([5,9,3,4,8,6])

cond = np.array([True, True, False, False, False, True])      

np.where(cond,b,a)                                                              # Picks a or b element depending on condition True or False

array([5, 9, 6, 7, 1, 6])

In [ ]:
a = np.array([2,9,6,7,1,5])

np.where(a<3,a,3)                                                               # Replace > 3 by 3

array([3, 9, 6, 7, 3, 5])

In [ ]:
a =np.arange(15)
b = np.add.reduce(a)                                                            # Add all the elements of the matrix
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
105


In [ ]:
a =np.arange(2,8)
b = np.multiply.reduce(a)                                                       # Multiply all the elements of the Matrix
print(a)
print(b)

# Polynomials

In [9]:
Polynomial = np.polynomial.Polynomial
X= np.array([0,20,40,60,80,100,120,140,160,180]) # X represents the equation coefficients 
Y= np.array([10,9,8,7,6,5,4,3,2,1])              # Y represents the equation results  
points,stats = Polynomial.fit(X,Y,1,full=True)# Get the best fit line that represents the equation of X and Y
print(points)                 # Points represents the slope and the cut of part of vetical axis


5.500000000000001 - 4.500000000000003·x¹


In [12]:
a = np.poly1d((-7))                                   # Construct an equation of zero degree                                                      
b = np.poly1d((-7,2))                                 # Construct an equation of first degree
c = np.poly1d((-7,2,1))                               # Construct an equation of second degree
d = np.poly1d((-7,2,1,3))                             # Construct an equation of third degree                                   
e = np.poly1d((-7,2,1,3,6))                           # Construct an equation of fifth degree
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


 
-7
-------------------------
 
-7 x + 2
-------------------------
    2
-7 x + 2 x + 1
-------------------------
    3     2
-7 x + 2 x + 1 x + 3
-------------------------
    4     3     2
-7 x + 2 x + 1 x + 3 x + 6


In [15]:
a=np.poly1d((-7,2,1,3,6))      # Construct an Equation of fourth degree
b=a(5)                               
c=a(0)                         # Substitution in the equation with some numbers
d=a(-15)
print(a)
print('-------------------------------')
print(b)
print('-------------------------------')
print(c)
print('-------------------------------')
print(d)



    4     3     2
-7 x + 2 x + 1 x + 3 x + 6
-------------------------------
-4079
-------------------------------
6
-------------------------------
-360939


In [16]:
a =np.polyder(np.poly1d((1,2,3)))       # derivation for one time to second degree equation
b =np.polyder(np.poly1d((1,2,3)),2)     # derivation for two times to second degree equation
c =np.polyder(np.poly1d((1,2,3)),3)     # derivation for three times to second degree equation
d =np.polyder(np.poly1d((1,2,3,5,12)))  # derivation for one time to fourth degree equation
e =np.polyder(np.poly1d((1,2,3,5,12)),3)# derivation for three times to fourth degree equation
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


 
2 x + 2
-------------------------
 
2
-------------------------
 
0
-------------------------
   3     2
4 x + 6 x + 6 x + 5
-------------------------
 
24 x + 12


In [17]:
# Substitution in the previous derived equations with some numbers
print(a(2))
print('-------------------------------')
print(b(0))   
print('-------------------------------') 
print(c(3))
print('-------------------------------')
print(d(-1))
print('-------------------------------')
print(e(5))


6
-------------------------------
2
-------------------------------
0
-------------------------------
1
-------------------------------
132


In [18]:
a =np.polyint(np.poly1d((1,2,3)))
b =np.polyint(np.poly1d((1,2,3)),2)
c =np.polyint(np.poly1d((1,2,3)),3)
d =np.polyint(np.poly1d((1,2,3,5,12)))
e =np.polyint(np.poly1d((1,2,3,5,12)),3)
print(a(2))
print('-------------------------')
print(b(0))
print('-------------------------')
print(c(3))
print('-------------------------')
print(d(-1))
print('-------------------------')
print(e(5))

12.666666666666666
-------------------------
0.0
-------------------------
24.300000000000004
-------------------------
-10.2
-------------------------
1168.8988095238094


In [19]:
a =np.polyint(np.poly1d((1,2,3)))       # Integration for one time to second degree equation
b =np.polyint(np.poly1d((1,2,3)),2)     # Integration for two times to second degree equation
c =np.polyint(np.poly1d((1,2,3)),3)     # Integration for three times to second degree equation
d =np.polyint(np.poly1d((1,2,3,5,12)))  # Integration for one time to fourth degree equation
e =np.polyint(np.poly1d((1,2,3,5,12)),3)# Integration for three times to fourth degree equation
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)


        3     2
0.3333 x + 1 x + 3 x
-------------------------
         4          3       2
0.08333 x + 0.3333 x + 1.5 x
-------------------------
         5           4       3
0.01667 x + 0.08333 x + 0.5 x
-------------------------
     5       4     3       2
0.2 x + 0.5 x + 1 x + 2.5 x + 12 x
-------------------------
          7           6        5          4     3
0.004762 x + 0.01667 x + 0.05 x + 0.2083 x + 2 x


In [20]:
# Substitution in the previous integrated equations with some numbers
print(a(2))
print('-------------------------------')
print(b(0))   
print('-------------------------------') 
print(c(3))
print('-------------------------------')
print(d(-1))
print('-------------------------------')
print(e(5))


12.666666666666666
-------------------------------
0.0
-------------------------------
24.300000000000004
-------------------------------
-10.2
-------------------------------
1168.8988095238094


In [23]:
# Get the Solutions of the radical equations
a = np.roots(np.poly1d((1,2)))
b = np.roots(np.poly1d((1,2,3)))      
c = np.roots(np.poly1d((1,2,3,5)))
d = np.roots(np.poly1d((1,2,3,5,12)))
e = np.roots(np.poly1d((1,2,3,5,12,22)))
print(a)
print('-------------------------')
print(b)
print('-------------------------')
print(c)
print('-------------------------')
print(d)
print('-------------------------')
print(e)




[-2.]
-------------------------
[-1.+1.41421356j -1.-1.41421356j]
-------------------------
[-1.84373428+0.j         -0.07813286+1.64492638j -0.07813286-1.64492638j]
-------------------------
[-1.61635728+1.15083694j -1.61635728-1.15083694j  0.61635728+1.63342631j
  0.61635728-1.63342631j]
-------------------------
[ 0.98732723+1.53502015j  0.98732723-1.53502015j -1.06743101+1.56536107j
 -1.06743101-1.56536107j -1.83979245+0.j        ]
